---
- hosts: docker
  become: yes

  vars_prompt:
  - name: username
    prompt: "What's the docker admin's user? (leave empty if you plan to use root)"
    private: no

  - name: swarm_conf
    prompt: "Do you want to cofigure Docker Swarm? (y/n)"
    private: no

  - name: manager_host
    prompt: "If you want a Docker Swarm, which node will be the manager node? (Please use inventory hostname)"
    private: no

  roles:
    #- { role: install_docker }
    - { role: configure_swarm, when: (swarm_conf|lower == 'y') or (swarm_conf|lower == 'yes') }
