---
- hosts: docker
  become: yes

  vars_prompt:
  - name: master_node
    prompt: "Which node is the master node? (If left empty, a random host will be selected)"
    private: no

  tasks:

  - name: Check IP addresses
    debug:
      var: hostvars['{{ master_node }}']['ansible_default_ipv4']['address']

  - name: Configure Docker Swarm
    docker_swarm:
      state: present
