- name: Initiate Swarm on Master Node
  shell: "docker swarm init --advertise-addr {{ ansible_default_ipv4.address }}"

- name: Register the token for joining the Swarm
  shell: "docker swarm join-token worker | grep join"
  register: worker_token

- name: Set token as a fact
  set_fact: docker_join_token="{{worker_token}}"

- name: Debug
  debug:
    msg: "{{worker_token}}"
